# PMOD A for tens digit
set_property PACKAGE_PIN Y18 [get_ports {seg_tens[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[0]}]
set_property PACKAGE_PIN Y19 [get_ports {seg_tens[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[1]}]
set_property PACKAGE_PIN Y16 [get_ports {seg_tens[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[2]}]
set_property PACKAGE_PIN Y17 [get_ports {seg_tens[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[3]}]
set_property PACKAGE_PIN U18 [get_ports {seg_tens[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[4]}]
set_property PACKAGE_PIN U19 [get_ports {seg_tens[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[5]}]
set_property PACKAGE_PIN W18 [get_ports {seg_tens[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_tens[6]}]

# PMOD B for ones digit
set_property PACKAGE_PIN W14 [get_ports {seg_ones[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[0]}]
set_property PACKAGE_PIN Y14 [get_ports {seg_ones[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[1]}]
set_property PACKAGE_PIN T11 [get_ports {seg_ones[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[2]}]
set_property PACKAGE_PIN T10 [get_ports {seg_ones[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[3]}]
set_property PACKAGE_PIN V16 [get_ports {seg_ones[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[4]}]
set_property PACKAGE_PIN W16 [get_ports {seg_ones[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[5]}]
set_property PACKAGE_PIN V12 [get_ports {seg_ones[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ones[6]}]
